"""initial onboarding schema

Revision ID: 0531530a4287
Revises: c447d92bb291
Create Date: 2026-01-08 17:05:25.098307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0531530a4287'
down_revision: Union[str, Sequence[str], None] = 'c447d92bb291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('csr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_id'), 'csr', ['id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('pan_card_file', sa.String(length=255), nullable=True),
    sa.Column('resume_file', sa.String(length=255), nullable=False),
    sa.Column('photo_file', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('highest_qualification', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=150), nullable=True),
    sa.Column('college', sa.String(length=150), nullable=True),
    sa.Column('year_of_passing', sa.Integer(), nullable=True),
    sa.Column('position_applied', sa.String(length=150), nullable=True),
    sa.Column('preferred_work_mode', sa.String(length=50), nullable=True),
    sa.Column('key_skills', sa.Text(), nullable=True),
    sa.Column('expected_salary', sa.Integer(), nullable=True),
    sa.Column('why_hire_me', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('previous_company', sa.String(length=150), nullable=True),
    sa.Column('previous_role', sa.String(length=150), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('relieving_date', sa.Date(), nullable=True),
    sa.Column('captcha_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('work_mode', sa.String(length=50), nullable=True),
    sa.Column('roles_responsibilities', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('experience_min', sa.Integer(), nullable=True),
    sa.Column('experience_max', sa.Integer(), nullable=True),
    sa.Column('qualification_required', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('perks_benefits', sa.Text(), nullable=True),
    sa.Column('job_summary', sa.Text(), nullable=True),
    sa.Column('job_location', sa.String(length=100), nullable=True),
    sa.Column('job_locality', sa.String(length=100), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('marital_status', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('aadhar_number', sa.String(length=20), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('communication_address', sa.Text(), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=False),
    sa.Column('landline_number', sa.String(length=20), nullable=True),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact1', sa.String(length=15), nullable=False),
    sa.Column('emergency_contact2', sa.String(length=15), nullable=True),
    sa.Column('education_qualification', sa.String(length=255), nullable=True),
    sa.Column('driving_license', sa.String(length=50), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('applied_role', sa.String(length=255), nullable=False),
    sa.Column('experience_type', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_role', sa.String(length=255), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('date_of_exit', sa.Date(), nullable=True),
    sa.Column('total_experience', sa.String(length=255), nullable=True),
    sa.Column('esi_number', sa.String(length=255), nullable=True),
    sa.Column('uan_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar_number'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_onboarding_id'), 'onboarding', ['id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_table('onboarding_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=255), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_bank_id'), 'onboarding_bank', ['id'], unique=False)
    op.create_table('onboarding_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_type', sa.String(length=20), nullable=False),
    sa.Column('aadhar_card', sa.Boolean(), nullable=True),
    sa.Column('pan_card', sa.Boolean(), nullable=True),
    sa.Column('qualification_certificates', sa.Boolean(), nullable=True),
    sa.Column('passport_size', sa.Boolean(), nullable=True),
    sa.Column('bank_account', sa.Boolean(), nullable=True),
    sa.Column('employer_reference_check', sa.Boolean(), nullable=True),
    sa.Column('relieving_letter', sa.Boolean(), nullable=True),
    sa.Column('pay_slips', sa.Boolean(), nullable=True),
    sa.Column('offer_letter', sa.Boolean(), nullable=True),
    sa.Column('hike_letter', sa.Boolean(), nullable=True),
    sa.Column('experience_letter', sa.Boolean(), nullable=True),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_checklist_id'), 'onboarding_checklist', ['id'], unique=False)
    op.create_table('onboarding_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_documents_id'), 'onboarding_documents', ['id'], unique=False)
    op.create_table('onboarding_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_family_id'), 'onboarding_family', ['id'], unique=False)
    op.create_table('onboarding_nominees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nominee_type', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_nominees_id'), 'onboarding_nominees', ['id'], unique=False)
    op.create_table('onboarding_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation_or_occupation', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('last_employer', sa.String(length=255), nullable=True),
    sa.Column('onboarding_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboarding_id'], ['onboarding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_references_id'), 'onboarding_references', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_references_id'), table_name='onboarding_references')
    op.drop_table('onboarding_references')
    op.drop_index(op.f('ix_onboarding_nominees_id'), table_name='onboarding_nominees')
    op.drop_table('onboarding_nominees')
    op.drop_index(op.f('ix_onboarding_family_id'), table_name='onboarding_family')
    op.drop_table('onboarding_family')
    op.drop_index(op.f('ix_onboarding_documents_id'), table_name='onboarding_documents')
    op.drop_table('onboarding_documents')
    op.drop_index(op.f('ix_onboarding_checklist_id'), table_name='onboarding_checklist')
    op.drop_table('onboarding_checklist')
    op.drop_index(op.f('ix_onboarding_bank_id'), table_name='onboarding_bank')
    op.drop_table('onboarding_bank')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_onboarding_id'), table_name='onboarding')
    op.drop_table('onboarding')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_csr_id'), table_name='csr')
    op.drop_table('csr')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
